apiVersion: v1
kind: Secret
metadata:
  name: exporter-msr-monitoring-secret
  namespace: monitor
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg==
  password: bWFuYWdl
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: exporter-msr-monitoring
  namespace: monitor
  labels:
    release: kube-prometheus
spec:
  jobLabel: msr
  selector:
    matchLabels:
      app: softwareag-bookstore
  endpoints:
  - port: api
    path: /metrics
    interval: 15s
    basicAuth:
      username:
        name: exporter-msr-monitoring-secret
        key: username
      password:
        name: exporter-msr-monitoring-secret
        key: password